#PBS -lselect=1:ncpus=2:mem=8gb
#PBS -lwalltime=24:00:00
#PBS -J 1-200
cd /rds/general/user/mq421/ephemeral
mkdir AA_d_P_1/
cd AA_d_P_1
mkdir ${PBS_ARRAY_INDEX}/
cd ${PBS_ARRAY_INDEX}
cp $PBS_O_WORKDIR/mmpbsa.in gbin.in
frame1=$((${PBS_ARRAY_INDEX}*30-29))
frame2=$((${PBS_ARRAY_INDEX}*30))
sed -ie s/FRAME1/$frame1/g gbin.in
sed -ie s/FRAME2/$frame2/g gbin.in

/rds/general/user/mq421/home/anaconda3/bin/MMPBSA.py \
   -i gbin.in \
   -o MMGBSA.dat \
   -cp $PBS_O_WORKDIR/complex.parm7 \
   -rp $PBS_O_WORKDIR/receptor.parm7 \
   -lp $PBS_O_WORKDIR/ligand.parm7 \
   -y $PBS_O_WORKDIR/*.nc \
   -eo energy.csv

rm *.nc.*
rm *.pdb
rm *.inpcrd
rm reference.frc
mkdir $PBS_O_WORKDIR/${PBS_ARRAY_INDEX}_2/
cp * $PBS_O_WORKDIR/${PBS_ARRAY_INDEX}_2/

cd $PBS_O_WORKDIR
rm AA_P.pbs.*
